environment:
  matrix:
    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python39-x64"

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: "3.9"
      coverage: 1

stack: python %PYTHON%
build: off

for:
  -
    matrix:
      only:
        - job_group: tests
    install:
      - sh: pip install virtualenv
      - sh: wget https://downloads.python.org/pypy/pypy3.7-v7.3.2-linux64.tar.bz2 -O pypy.tar.bz2
      - sh: tar -xf pypy.tar.bz2
      - sh: rm -f *.tar.bz2
      - sh: virtualenv -p pypy3*-*/bin/pypy pypy
      - sh: source pypy/bin/activate
      - sh: pypy -m ensurepip
      - sh: pypy -m pip install numpy

      - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
      - cmd: python --version
      - cmd: pip install numpy
    test_script:
      - sh: pypy -c "import numpy"
      - cmd: python -c "import numpy"
    on_success:
      - echo "SUCCESS!"
