environment:
  matrix:
    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: 'C:\\Python39-x64'

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: 'C:\\Python38-x64'

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: 'C:\\Python37-x64'

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: '3.9'
      coverage: 1

stack: python %PYTHON%
build: off

for:
  -
    matrix:
      only:
        - job_group: tests
    install:
      - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
      - python --version
      - pip install libpcap
      - sh: sudo setcap cap_net_raw+eip "$(readlink -f $(command -v python))"
      # Configure the NPF driver
      - ps: cinst wireshark -y
    test_script:
      - python --version
      - python test.py
    on_success:
      - echo 'SUCCESS!'
