environment:
  matrix:
    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python39-x64"

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: "3.9"
      coverage: 1

stack: python %PYTHON%
build: off

for:
  -
    matrix:
      only:
        - job_group: tests
    install:
      - sh: sudo add-apt-repository ppa:pypy/ppa
      - sh: sudo apt update
      - sh: sudo apt install -y pypy3
      - sh: pypy3 -m ensurepip
      - sh: pypy3 -m pip install numpy

      - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
      - cmd: python --version
      - cmd: pip install numpy
    test_script:
      - sh: pypy3 -c "import numpy"
      - cmd: python -c "import numpy"
    on_success:
      - echo "SUCCESS!"
