environment:
  matrix:
    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: 'C:\\Python39-x64'

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: 'C:\\Python38-x64'

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: 'C:\\Python37-x64'

    - job_group: tests
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: '3.9'
      coverage: 1

stack: python %PYTHON%
build: off

for:
  -
    matrix:
      only:
        - job_group: tests
    install:
      # Configure the NPF driver
      - cmd: 'curl.exe --output npcap.exe --url https://nmap.org/npcap/dist/npcap-0.96.exe'
      - cmd: 'npcap.exe /loopback_support=yes /winpcap_mode=yes /S'
      # The previous steps may have disrupted connectivity because installation of the NDIS driver does that on Windows.
      # Also, a restart appears to be necessary to enable the NPF service.
      # To fix that, restart VM as suggested in https://github.com/appveyor/ci/issues/3491.
      - cmd: 'shutdown /r /f /t 1'
      - cmd: 'timeout 30'
      # Configure the rest of the environment after the reboot.
      - cmd: 'set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%'
      - sh: sudo setcap cap_net_raw+eip "$(readlink -f $(command -v python))"
      - pip install libpcap
      - python --version
    test_script:
      - python test.py
    on_success:
      - echo 'SUCCESS!'
