name: Test

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testx
        run: |
            echo "Commit message: ${{ github.event.head_commit.message }}"
