name: Test
on: push
jobs:
  ci-diagnostics:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip --quiet --disable-pip-version-check install --upgrade --upgrade-strategy=eager nox
          nox --forcecolor --non-interactive
