name: Test

on: push

jobs:
  ci-diagnostics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ github.event.head_commit.message }}"
      - run: echo "${{ github.ref }}"
      - run: >
            echo "${{
            contains(github.event.head_commit.message, '#groom') ||
            contains(github.ref, 'master') ||
            contains(github.ref, 'release')
            }}"

  groom:
    runs-on: ubuntu-latest
    if: >
      contains(github.event.head_commit.message, '#groom') ||
      contains(github.ref, 'master') ||
      contains(github.ref, 'release')
    steps:
      - uses: actions/checkout@v2
      - name: Testx
        run: |
            echo "Commit message: ${{ github.event.head_commit.message }}"

      - name: Upload diagnostic snapshot with ${{ 2 + 8 * failure() }}-day retention
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: workspace-${{github.job}}
          path: "*"
          retention-days: ${{ 2 + 8 * failure() }}

  sonarcloud:
    runs-on: ubuntu-latest
    # don't run sonarcloud on builds originating from forks
    # due to secrets not being available
    if: secrets.FOO
    env:
      FOO_TOKEN: ${{ secrets.FOO }}
    steps:
    - run: echo "SECRET FOO: $FOO"

