name: Test
on: [push, pull_request]
jobs:
  ci-diagnostics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{github.event.head_commit.message}}"
          echo "${{github.event.pull_request.author_association}}"
          echo "${{toJSON(github.event)}}"
